In [2]:
import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib.colors as mcolors
import pandas as pd 
import random
import math
import time
from sklearn.linear_model import LinearRegression, BayesianRidge
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error

import operator 
plt.style.use('seaborn')
#import geopandas as gpd
import plotly.express as px
import plotly.graph_objs as go
import plotly.figure_factory as ff
%matplotlib inline 
pd.plotting.register_matplotlib_converters()
import seaborn as sns

import matplotlib.ticker as ticker
import matplotlib.animation as animation
import emoji
from IPython.display import HTML
import warnings
#warnings.filterwarnings('ignore')

from datetime import datetime
from scipy import stats
import statsmodels.api as sm
from statsmodels.graphics.api import qqplot
from matplotlib.pylab import rcParams
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import acf, pacf
#rcParams['figure.figsize'] = 30, 10

import pyramid as pm
#from pyramid.arima import auto_arima
from pmdarima.arima import auto_arima
from scipy.optimize import curve_fit


print("Setup Complete")

Setup Complete

In [29]:
conf_df = pd.read_csv('C:\\Users\\Raushan Kumar\\Downloads\\Covid19-master\\Covid19-master\\time_series_covid19_confirmed_global.csv')
death_df = pd.read_csv('C:\\Users\\Raushan Kumar\\Downloads\\Covid19-master\\Covid19-master\\time_series_covid19_deaths_global.csv')
reco_df = pd.read_csv('C:\\Users\\Raushan Kumar\\Downloads\\Covid19-master\\Covid19-master\\time_series_covid19_recovered_global.csv')

In [30]:
conf_df=conf_df.fillna(0)
death_df=death_df.fillna(0)
reco_df=reco_df.fillna(0)

In [31]:
conf1=conf_df[conf_df.columns[0:4:]]
conf = conf_df[conf_df.columns[4:]]
conf=conf.T
conf=conf.diff()
conf=conf.iloc[1::, :]
conf=conf.T
conf_df=pd.concat([pd.DataFrame(conf1),pd.DataFrame(conf_df.iloc[:,4]),conf],axis=1)

In [32]:
Death1=death_df[death_df.columns[0:4:]]
death=death_df[death_df.columns[4:]]
death=death.T
death=death.diff()
death=death.iloc[1::, :]
death=death.T
death_df=pd.concat([pd.DataFrame(Death1),pd.DataFrame(death_df.iloc[:,4]),death],axis=1)

In [33]:
reco1=reco_df[reco_df.columns[0:4:]]
reco=reco_df[reco_df.columns[4:]]
reco=reco.T
reco=reco.diff()
reco=reco.iloc[1::, :]
reco=reco.T
reco_df=pd.concat([pd.DataFrame(reco1),pd.DataFrame(reco_df.iloc[:,4]),reco],axis=1)

In [9]:
import sys
pd.set_option('display.max_rows', 1000)
np.set_printoptions(threshold=sys.maxsize)

In [35]:
full_table.to_csv('rec5.csv')

In [40]:
my=[2660,30360]
recv_df_long[recv_df_long.index.isin(my)]

     Province/State Country/Region   Lat  Long    Date  Recovered
2660              0         Israel  31.0  35.0  2/1/20        0.0

In [34]:
#extracting all the dates
dates = conf_df.columns[4:]

#making new dataframes for confiremed ,death and recovred cases
conf_df_long = conf_df.melt(id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
                            value_vars=dates, var_name='Date', value_name='Confirmed')

deaths_df_long = death_df.melt(id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
                            value_vars=dates, var_name='Date', value_name='Deaths')

recv_df_long = reco_df.melt(id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
                            value_vars=dates, var_name='Date', value_name='Recovered')

#full table combinig all confirmed,recovered and deaths 
full_table = pd.concat([conf_df_long, deaths_df_long['Deaths'], recv_df_long['Recovered']], 
                       axis=1, sort=False)

full_table.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered
0,0,Afghanistan,33.0000,65.0000,1/22/20,0.0,0.0,0.0
1,0,Albania,41.1533,20.1683,1/22/20,0.0,0.0,0.0
2,0,Algeria,28.0339,1.6596,1/22/20,0.0,0.0,0.0
3,0,Andorra,42.5063,1.5218,1/22/20,0.0,0.0,0.0
4,0,Angola,-11.2027,17.8739,1/22/20,0.0,0.0,0.0

In [ ]:
recv_df_long.to_csv('test.csv')

In [333]:
cases = ['Confirmed', 'Deaths', 'Recovered', 'Active']
#adding active cases to the dataset

full_table['Active'] = full_table['Confirmed'] - full_table['Deaths'] - full_table['Recovered']

In [400]:
#my=[30360]
#full_table[full_table.index.isin(my)]
reco_df[reco_df['Country/Region'].str.contains('Afghanistan')==True]

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/11/20,5/12/20,5/13/20,5/14/20,5/15/20,5/16/20,5/17/20,5/18/20,5/19/20,5/20/20
0,NaN,Afghanistan,33.0,65.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,52.0,38.0,43.0,54.0,0.0,33.0,23.0,49.0,80.0

In [394]:
full_table.to_csv('act.csv')

In [334]:
#Cleaning 

#full_table = full_table[full_table['Province/State'].str.contains(',')!=True]
full_table['Province/State'] = full_table['Province/State'].replace('Bonaire, Sint Eustatius and Saba', 'Sint Eustatius and Saba Bonaire')
full_table['Country/Region'] = full_table['Country/Region'].replace('Korea, South', 'South Korea')
full_table['Country/Region'] = full_table['Country/Region'].replace('Mainland China', 'China')



#full_table.to_csv('covid_19_full_updatedNew.csv', index=False)

In [335]:
#current_date,according to dataset
today = dates[-1]
#full latest keeps today's data for all countries
full_latest = full_table[full_table['Date'] == today].reset_index()

In [336]:
#list_1=[30360]
#full_latest_grouped[full_latest_grouped.index.isin(list_1)]

In [358]:
full_latest_grouped = full_table.groupby('Country/Region')['Confirmed', 'Deaths', 'Recovered', 'Active'].sum().reset_index()
temp_f = full_latest_grouped.sort_values(by='Confirmed', ascending=False)
temp_f = temp_f.reset_index(drop=True)
temp_f.head(10).style.background_gradient(cmap='Reds')

In [359]:
full_latest_grouped = full_table.groupby('Country/Region')['Confirmed', 'Deaths', 'Recovered', 'Active'].sum().reset_index()
temp_g = full_latest_grouped.sort_values(by='Recovered', ascending=False)
temp_g = temp_g.reset_index(drop=True)
temp_g.head(10).style.background_gradient(cmap='Greens')

In [362]:
cols=conf_df.keys()

In [366]:
conf = conf_df.loc[:, cols[4]:cols[-1]]
death = death_df.loc[:, cols[4]:cols[-1]]
reco = reco_df.loc[:, cols[4]:cols[-1]]

In [369]:
conf.keys()

Index(['1/22/20', '1/23/20', '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       '1/28/20', '1/29/20', '1/30/20', '1/31/20',
       ...
       '5/11/20', '5/12/20', '5/13/20', '5/14/20', '5/15/20', '5/16/20',
       '5/17/20', '5/18/20', '5/19/20', '5/20/20'],
      dtype='object', length=120)

In [371]:
conf['1/22/20'].sum()

555

In [372]:
dates = conf.keys()
world_cases = []
total_deaths = [] 
mortality_rate = []
recovery_rate = [] 
total_recovered = [] 
total_active = [] 

india_cases_conf = []
india_cases_reco = []
india_cases_death = []
india_cases_active = []

j=0
for i in dates:
    
    confirmed_sum = conf[i].sum()
    death_sum = death[i].sum()
    recovered_sum = reco[i].sum()
    
    # confirmed, deaths, recovered, and active
    world_cases.append(confirmed_sum)
    total_deaths.append(death_sum)
    total_recovered.append(recovered_sum)
    total_active.append(confirmed_sum-death_sum-recovered_sum)
    
    # calculate rates
    mortality_rate.append(death_sum/confirmed_sum)
    recovery_rate.append(recovered_sum/confirmed_sum)

    # case studies 
    #china_cases.append(conf_df[conf_df['Country/Region']=='China'][i].sum())
    #italy_cases.append(conf_df[conf_df['Country/Region']=='Italy'][i].sum())
#     india_cases_conf.append(conf_df[conf_df['Country/Region']=='India'][i].sum())
#     india_cases_reco.append(reco_df[reco_df['Country/Region']=='India'][i].sum())
#     india_cases_death.append(death_df[death_df['Country/Region']=='India'][i].sum())
#     india_cases_active.append(india_cases_conf[j] - india_cases_reco[j] - india_cases_death[j])
    
    j = j+1

In [381]:
#total confirmed cases in the world
world_df = pd.DataFrame(index=dates,data=world_cases, columns=['conf_cases'])
world_df['daily_new_cases'] = world_df['conf_cases']

In [383]:
total_death_df = pd.DataFrame(index=dates,data=total_deaths, columns=['total_death'])
total_death_df['new_death'] = total_death_df['total_death']

In [388]:
total_reco_df = pd.DataFrame(index=dates,data=total_recovered, columns=['total_recovered'])
total_reco_df['new_reco'] = total_reco_df['total_recovered']

In [392]:
total_active_df

         total_active  new_active
1/22/20         510.0       510.0
1/23/20          96.0        96.0
1/24/20         273.0       273.0
1/25/20         474.0       474.0
1/26/20         657.0       657.0
1/27/20         774.0       774.0
1/28/20        2556.0      2556.0
1/29/20         567.0       567.0
1/30/20        2013.0      2013.0
1/31/20        1572.0      1572.0
2/1/20         2003.0      2003.0
2/2/20         4458.0      4458.0
2/3/20         2879.0      2879.0
2/4/20         3716.0      3716.0
2/5/20         3399.0      3399.0
2/6/20         2726.0      2726.0
2/7/20         2988.0      2988.0
2/8/20         2037.0      2037.0
2/9/20         2302.0      2302.0
2/10/20        1803.0      1803.0
2/11/20        1203.0      1203.0
2/12/20         -53.0       -53.0
2/13/20       13749.0     13749.0
2/14/20        4602.0      4602.0
2/15/20         665.0       665.0
2/16/20         620.0       620.0
2/17/20         218.0       218.0
2/18/20         -30.0       -30.0
2/19/20       -1381.0     -1381.0
2/20/20       -1623.0     -1623.0
2/21/20         -95.0       -95.0
2/22/20       -2450.0     -2450.0
2/23/20        -133.0      -133.0
2/24/20       -1390.0     -1390.0
2/25/20       -1912.0     -1912.0
2/26/20       -1559.0     -1559.0
2/27/20       -1579.0     -1579.0
2/28/20       -2126.0     -2126.0
2/29/20       -1241.0     -1241.0
3/1/20         -631.0      -631.0
3/2/20        -1038.0     -1038.0
3/3/20         -167.0      -167.0
3/4/20         -756.0      -756.0
3/5/20           49.0        49.0
3/6/20         1737.0      1737.0
3/7/20         1450.0      1450.0
3/8/20         1395.0      1395.0
3/9/20         1787.0      1787.0
3/10/20        2842.0      2842.0
3/11/20        4306.0      4306.0
3/12/20        1047.0      1047.0
3/13/20       14256.0     14256.0
3/14/20        8099.0      8099.0
3/15/20        7336.0      7336.0
3/16/20       11414.0     11414.0
3/17/20       11939.0     11939.0
3/18/20       14384.0     14384.0
3/19/20       24973.0     24973.0
3/20/20       25711.0     25711.0
3/21/20       26342.0     26342.0
3/22/20       24534.0     24534.0
3/23/20       38894.0     38894.0
3/24/20       28087.0     28087.0
3/25/20       40963.0     40963.0
3/26/20       50543.0     50543.0
3/27/20       51773.0     51773.0
3/28/20       55391.0     55391.0
3/29/20       45938.0     45938.0
3/30/20       42921.0     42921.0
3/31/20       56529.0     56529.0
4/1/20        54791.0     54791.0
4/2/20        57633.0     57633.0
4/3/20        60924.0     60924.0
4/4/20        53604.0     53604.0
4/5/20        54355.0     54355.0
4/6/20        49492.0     49492.0
4/7/20        43587.0     43587.0
4/8/20        48453.0     48453.0
4/9/20        53023.0     53023.0
4/10/20       62822.0     62822.0
4/11/20       46102.0     46102.0
4/12/20       73448.0     73448.0
4/13/20       37362.0     37362.0
4/14/20       38215.0     38215.0
4/15/20       35400.0     35400.0
4/16/20       58079.0     58079.0
4/17/20       52778.0     52778.0
4/18/20       47277.0     47277.0
4/19/20       47027.0     47027.0
4/20/20       43969.0     43969.0
4/21/20       35228.0     35228.0
4/22/20       38745.0     38745.0
4/23/20       48108.0     48108.0
4/24/20       30391.0     30391.0
4/25/20       51399.0     51399.0
4/26/20       41600.0     41600.0
4/27/20       36453.0     36453.0
4/28/20       33872.0     33872.0
4/29/20       26724.0     26724.0
4/30/20       13467.0     13467.0
5/1/20        44860.0     44860.0
5/2/20        36110.0     36110.0
5/3/20        43389.0     43389.0
5/4/20        34771.0     34771.0
5/5/20        37826.0     37826.0
5/6/20        40181.0     40181.0
5/7/20        44609.0     44609.0
5/8/20        49706.0     49706.0
5/9/20        27958.0     27958.0
5/10/20       40936.0     40936.0
5/11/20       24953.0     24953.0
5/12/20       41428.0     41428.0
5/13/20       24883.0     24883.0
5/14/20       50578.0     50578.0
5/15/20       45762.0     45762.0
5/16/20       31476.0     31476.0
5/17/20       35382.0     35382.0
5/18/20       32115.0     32115.0
5/19/20       38625.0     38625.0
5/20/20       35679.0     35679.0

In [391]:
total_active_df = pd.DataFrame(index=dates,data=total_active, columns=['total_active'])

#total_active_df['new_active111'] = world_df['daily_new_cases'] - total_death_df['new_death'] - total_reco_df['new_reco']
total_active_df['new_active'] = total_active_df['total_active']

In [390]:
world_full = pd.concat([world_df,total_reco_df,total_death_df,total_active_df], axis=1)

NameError: name 'total_active_df' is not defined

In [393]:
full_latest_grouped.to_csv('active.csv')